/* eslint-disable @typescript-eslint/no-explicit-any */
declare module '*.svg' {
  const content: any;
  export const ReactComponent: any;
  export const metadata = {
    title: 'Welcome to PrintVault',
    description: 'Generated by create-nx-workspace',
  };
  export default content;
}
